### ISSUE TITLE
Display macOS toolstate also

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/rust-toolstate#7]
Sometimes macOS might fail when Windows and Linux succeed, and it'd be great to capture that as part of the toolstate display.

**Comment by kennytm** [comment]
We don't test tools on macOS which is why we don't have their toolstates.

**Comment by jonathandturner** [comment]
@kennytm - do you know if we test if macOS is succeeding installs elsewhere?

background: looks like we're unfortunately failing to install on macOS with the most recent nightly.

**Comment by kennytm** [comment]
@jonathandturner For whether a component exists you could check https://mexus.github.io/rustup-components-history/x86_64-apple-darwin.html. The current macOS issue is rust-lang/rust#55571 and is irrelevant to the tools.

**Comment by jonathandturner** [comment]
Thanks, sorry for the noise
